baseURL = "http://ngregorich.github.io/funwithhardware"
languageCode = "en-us"
title = "Fun With Hardware"
theme = "hugo.386"
publishDir = "docs"

[params]
    # The name to display as main title in the home page
    mainpagetitle = "Fun With Hardware"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Dear diary, today I blinked an LED." 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "A public display of learning and experimentation. What could go wrong?"

    # The name to display in the copyright section in the footer
    copyrightname = "Nicholas Gregorich"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "http://ngregorich.github.io/funwithhardware"

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Urls for social networks
    linkedin = "https://www.linkedin.com/in/nicholas-gregorich-4985754b/"
    github = "https://github.com/ngregorich"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 9.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = true

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true