baseURL = "http://ngregorich.github.io/funwithhardware/"
languageCode = "en-us"
title = "Fun With Hardware"
theme="archie"
copyright = "© Nicholas Gregorich"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	featherIconsCDN=true
	subtitle = "A public display of learning and experimentation. What could go wrong?"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/nicholas-gregorich-4985754b/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ngregorich"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
